name = "bookspank-site"
main = "src/index.js"
compatibility_date = "2024-12-01"

# Development KV namespace
[[kv_namespaces]]
binding = "BOOKCLUB_KV"
id = "bca02def9c1746dca69cf7447400aca2"

[env.production]
routes = [
  { pattern = "bookspank.com", custom_domain = true },
  { pattern = "www.bookspank.com", custom_domain = true }
]

# Production KV namespace
[[env.production.kv_namespaces]]
binding = "BOOKCLUB_KV"
id = "b6b68b3f6b1a4d6c9265938572d01b3b"